# Generated by Django 5.0.3 on 2024-03-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathfinder', '0004_grid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grid',
            name='grid_data',
        ),
        migrations.AddField(
            model_name='grid',
            name='grid_image',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
