# Generated by Django 5.0.3 on 2024-03-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathfinder', '0005_remove_grid_grid_data_grid_grid_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='grid_algorithm',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='grid',
            name='grid_maze',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='grid',
            name='grid_speed',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
