# Generated by Django 5.0.3 on 2024-03-26 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathfinder', '0006_grid_grid_algorithm_grid_grid_maze_grid_grid_speed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grid',
            old_name='grid_algorithm',
            new_name='algorithm',
        ),
        migrations.RenameField(
            model_name='grid',
            old_name='grid_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='grid',
            old_name='grid_maze',
            new_name='maze',
        ),
        migrations.RenameField(
            model_name='grid',
            old_name='grid_speed',
            new_name='speed',
        ),
    ]
