# Generated by Django 5.0.3 on 2024-03-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathfinder', '0007_rename_grid_algorithm_grid_algorithm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./media'),
        ),
    ]
