# Generated by Django 5.0.3 on 2024-03-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathfinder', '0009_alter_grid_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='grids/'),
        ),
    ]
